/* Generated By:JJTree: Do not edit this line. NodePrintStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Node,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.schotanus.turtle.parser;

public
class NodePrintStatement extends SimpleNode {
  public NodePrintStatement(int id) {
    super(id);
  }

  public NodePrintStatement(TurtleParser p, int id) {
    super(p, id);
  }

  public void interpret() throws InterpretationException {
    for (int i = 0; i < jjtGetNumChildren(); i++) {
        jjtGetChild(i).interpret();
        System.out.print(expressionStack.pop());
    }
    System.out.println();
  }
}
/* JavaCC - OriginalChecksum=92b64132752c3026f82a7e2067f580c7 (do not edit this line) */
