/* Generated By:JJTree: Do not edit this line. NodeLessThanExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Node,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.schotanus.turtle.parser;

public
class NodeLessThanExpression extends SimpleNode {
  public NodeLessThanExpression(int id) {
    super(id);
  }

  public NodeLessThanExpression(TurtleParser p, int id) {
    super(p, id);
  }

  public void interpret() throws InterpretationException {
    jjtGetChild(0).interpret();
    double leftOperand = ((Double)expressionStack.pop()).doubleValue();

    jjtGetChild(1).interpret();
    double rightOperand = ((Double)expressionStack.pop()).doubleValue();

    expressionStack.push(new Boolean(leftOperand < rightOperand));
}
}
/* JavaCC - OriginalChecksum=5973ba115e2a24a93dc38f955aabeabf (do not edit this line) */
