/* Generated By:JJTree: Do not edit this line. NodeFormalArguments.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Node,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.schotanus.turtle.parser;

public
class NodeFormalArguments extends SimpleNode {
  public NodeFormalArguments(int id) {
    super(id);
  }

  public NodeFormalArguments(TurtleParser p, int id) {
    super(p, id);
  }

  /**
   * Interprets the optional formal arguments belonging to a function.
   * Formal arguments are separated by whitespace.
   * Currently this method does not perform any interpretation at all but
   * future implementations might for example check for duplicate declaration
   * of formal arguments.
   * @pending Interpretation of formal arguments.
   */
  public void interpret() {
    // Empty implementation
  }
}
/* JavaCC - OriginalChecksum=c11725a495f2cd12f2e08fdd01b4366d (do not edit this line) */
