/* Generated By:JJTree: Do not edit this line. NodeSineFunction.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Node,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.schotanus.turtle.parser;

public
class NodeSineFunction extends SimpleNode {
  public NodeSineFunction(int id) {
    super(id);
  }

  public NodeSineFunction(TurtleParser p, int id) {
    super(p, id);
  }

  /**
   * Interprets: SIN(expression) where expression is the one and only child.
   * <br>The expression is interpreted and popped from the stack. The sine
   * of the popped value is calculated (in degrees) and pushed on the stack.
   */
  public void interpret() throws InterpretationException {
    jjtGetChild(0).interpret();

    double value = ((Double)expressionStack.pop()).doubleValue();
    expressionStack.push(new Double(Math.sin(Math.toRadians(value))));
  }
}
/* JavaCC - OriginalChecksum=04bd64482300d0053d2dfd648af008a2 (do not edit this line) */
