/* Generated By:JJTree: Do not edit this line. NodeActualArguments.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Node,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.schotanus.turtle.parser;

public
class NodeActualArguments extends SimpleNode {
  public NodeActualArguments(int id) {
    super(id);
  }

  public NodeActualArguments(TurtleParser p, int id) {
    super(p, id);
  }

  /**
   * Dummy interpret method. The actual interpretation takes place in class
   * {@link NodeFunctionCall}.
   * @throws InterpretationException Whenever this method is called.
   */
  public void interpret() throws InterpretationException {
    throw new InterpretationException("NodeActualArguments::interpret():" + "Should never be called!");
  }
}
/* JavaCC - OriginalChecksum=4d8f9abe8bfee4fd3931bdfbd36807f8 (do not edit this line) */
