/* Generated By:JJTree: Do not edit this line. NodePenPositionStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Node,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.schotanus.turtle.parser;

public
class NodePenPositionStatement extends SimpleNode {
  public NodePenPositionStatement(int id) {
    super(id);
  }

  public NodePenPositionStatement(TurtleParser p, int id) {
    super(p, id);
  }

  public void interpret() throws InterpretationException {
    jjtGetChild(0).interpret();
    double x = ((Double)expressionStack.pop()).doubleValue();

    jjtGetChild(1).interpret();
    double y = ((Double)expressionStack.pop()).doubleValue();
    getActiveTurtleModel().setPosition(x, y);
  }
}
/* JavaCC - OriginalChecksum=ccc087fcbf7a045fef6cdbcf353b039a (do not edit this line) */
