/* Generated By:JJTree: Do not edit this line. NodeSubtractExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Node,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.schotanus.turtle.parser;

public
class NodeSubtractExpression extends SimpleNode {
  public NodeSubtractExpression(int id) {
    super(id);
  }

  public NodeSubtractExpression(TurtleParser p, int id) {
    super(p, id);
  }
  
  public void interpret() throws InterpretationException {
    jjtGetChild(0).interpret();
    double leftOperand = ((Double)expressionStack.pop()).doubleValue();

    jjtGetChild(1).interpret();
    double rightOperand = ((Double)expressionStack.pop()).doubleValue();

    expressionStack.push(Double.valueOf(leftOperand - rightOperand));
  }
}
/* JavaCC - OriginalChecksum=de035175f5416991129570807923b916 (do not edit this line) */
