/* Generated By:JJTree: Do not edit this line. NodePenColorStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Node,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.schotanus.turtle.parser;

import java.awt.Color;


public class NodePenColorStatement extends SimpleNode {
  public NodePenColorStatement(int id) {
    super(id);
  }

  public NodePenColorStatement(TurtleParser p, int id) {
    super(p, id);
  }

  public void interpret() throws InterpretationException {
    int [] colors = new int[3];

    for (int i = 0; i < 3; i++) {
      jjtGetChild(i).interpret();
      colors[i] = ((Double)expressionStack.peek()).intValue();
      if (colors[i] < 0) {
        colors[i] = 0;
      } else if (colors[i] > 255) {
        colors[i] = 255;
      }
    }
    getActiveTurtleModel().setColor(new Color(colors[0], colors[1], colors[2]));
  }
}
/* JavaCC - OriginalChecksum=d8108a4cf7c2bbec14b9386d52eb1161 (do not edit this line) */
