/* Generated By:JJTree: Do not edit this line. NodeGreaterThanExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Node,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.schotanus.turtle.parser;

public
class NodeGreaterThanExpression extends SimpleNode {
  public NodeGreaterThanExpression(int id) {
    super(id);
  }

  public NodeGreaterThanExpression(TurtleParser p, int id) {
    super(p, id);
  }

  /**
   * Interprets: expression1 > expression2
   * <br>Both expressions are interpreted and popped from the stack. The
   * Boolean result is pushed on the stack.
   */
  public void interpret() throws InterpretationException {
    jjtGetChild(0).interpret();
    double leftOperand = ((Double)expressionStack.pop()).doubleValue();
    jjtGetChild(1).interpret();
    double rightOperand = ((Double)expressionStack.pop()).doubleValue();
    expressionStack.push(Boolean.valueOf(leftOperand > rightOperand));
  }
}
/* JavaCC - OriginalChecksum=4d962cba95c3ef8447c607e64400b895 (do not edit this line) */
