/* Generated By:JJTree: Do not edit this line. NodeCosineFunction.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Node,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.schotanus.turtle.parser;

public
class NodeCosineFunction extends SimpleNode {
  public NodeCosineFunction(int id) {
    super(id);
  }

  public NodeCosineFunction(TurtleParser p, int id) {
    super(p, id);
  }

  /**
   * Interprets: COS(expression) where expression is the one and only child.
   * <br>The expression is interpreted and popped from the stack. The cosine
   * of the popped value is calculated (in degrees) and pushed on the stack.
   * @throws InterpretationException When an interpretation error occurs
   *  during the interpretation of the expression.
   */
  public void interpret() throws InterpretationException {
    jjtGetChild(0).interpret();

    double value = ((Double)expressionStack.pop()).doubleValue();
    expressionStack.push(new Double(Math.cos(Math.toRadians(value))));
  }

}
/* JavaCC - OriginalChecksum=1cab9c05a136bbd100b41a506681d582 (do not edit this line) */
