/* Generated By:JJTree: Do not edit this line. NodeHeadStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Node,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.schotanus.turtle.parser;

public
class NodeHeadStatement extends SimpleNode {
  public NodeHeadStatement(int id) {
    super(id);
  }

  public NodeHeadStatement(TurtleParser p, int id) {
    super(p, id);
  }

  /**
   * Interprets: HEAD expression.
   * <br>The expression is interpreted and popped from the stack. The popped
   * value is used to turn the active turtle.
   */
  public void interpret() throws InterpretationException {
    jjtGetChild(0).interpret();
    double heading = ((Double)expressionStack.pop()).doubleValue();
    getActiveTurtleModel().setHeading(heading);
  }
}
/* JavaCC - OriginalChecksum=41f486b8750aab6903f17c3760ea901a (do not edit this line) */
