/* Generated By:JJTree: Do not edit this line. NodePenXPositionStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Node,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.schotanus.turtle.parser;

public
class NodePenXPositionStatement extends SimpleNode {
  public NodePenXPositionStatement(int id) {
    super(id);
  }

  public NodePenXPositionStatement(TurtleParser p, int id) {
    super(p, id);
  }

  public void interpret() throws InterpretationException {
    jjtGetChild(0).interpret();
    double x = ((Double)expressionStack.pop()).doubleValue();

    getActiveTurtleModel().setXPosition(x);
  }
}
/* JavaCC - OriginalChecksum=7105751c448f0f1acf429d9232d9e927 (do not edit this line) */
