/* Generated By:JJTree: Do not edit this line. NodePenUpOrDownStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Node,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.schotanus.turtle.parser;

public
class NodePenUpOrDownStatement extends SimpleNode {
  private boolean down;

  public NodePenUpOrDownStatement(int id) {
    super(id);
  }

  public NodePenUpOrDownStatement(TurtleParser p, int id) {
    super(p, id);
  }

  public void setDown(final boolean down) {
    this.down = down;
  }

  public void interpret() {
    getActiveTurtleModel().setPenDown(down);
  }
}
/* JavaCC - OriginalChecksum=f4e03ad72dc6fc97612bf0b794efcd9d (do not edit this line) */
