/* Generated By:JJTree: Do not edit this line. NodeWhileStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Node,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.schotanus.turtle.parser;

public
class NodeWhileStatement extends SimpleNode {
  public NodeWhileStatement(int id) {
    super(id);
  }

  public NodeWhileStatement(TurtleParser p, int id) {
    super(p, id);
  }


  public void interpret() throws InterpretationException {
    jjtGetChild(0).interpret();
    boolean result = ((Boolean)expressionStack.pop()).booleanValue();

    while (result) {
      jjtGetChild(1).interpret();

      jjtGetChild(0).interpret();
      result = ((Boolean)expressionStack.pop()).booleanValue();
    }
  }
}
/* JavaCC - OriginalChecksum=7b5c142a663dbef93cb0fe5dee032337 (do not edit this line) */
