/* Generated By:JJTree: Do not edit this line. NodeAddExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Node,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.schotanus.turtle.parser;

public
class NodeAddExpression extends SimpleNode {
  public NodeAddExpression(int id) {
    super(id);
  }

  public NodeAddExpression(TurtleParser p, int id) {
    super(p, id);
  }

  /**
   * Interprets: expression1 + expression2
   * <br>Both expressions are interpreted and popped from the stack. The
   * result is pushed on the stack.
   * @throws InterpretationException When an error occurs when interpreting
   *  expression1 or expression2.
   */
  public void interpret() throws InterpretationException {
    jjtGetChild(0).interpret();
    double leftOperand = ((Double)expressionStack.pop()).doubleValue();

    jjtGetChild(1).interpret();
    double rightOperand = ((Double)expressionStack.pop()).doubleValue();

    expressionStack.push(new Double(leftOperand + rightOperand));
  }
}
/* JavaCC - OriginalChecksum=8439a5b71541d28a642acf173d2c9044 (do not edit this line) */
