/* Generated By:JJTree: Do not edit this line. NodeRepeatStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Node,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.schotanus.turtle.parser;

public
class NodeRepeatStatement extends SimpleNode {
  public NodeRepeatStatement(int id) {
    super(id);
  }

  public NodeRepeatStatement(TurtleParser p, int id) {
    super(p, id);
  }
  
  public void interpret() throws InterpretationException {
    jjtGetChild(0).interpret();
    int count = ((Double)expressionStack.pop()).intValue();

    repCountStack.push(Double.valueOf(1.0));
    for (int i = 0; i < count; i++) {
      jjtGetChild(1).interpret();
      double repCount = ((Double)repCountStack.pop()).doubleValue();
      repCountStack.push(Double.valueOf(++repCount));
    }
    repCountStack.pop();
  }
}
/* JavaCC - OriginalChecksum=bdd2faf474d3d0ad4667f86626cc3610 (do not edit this line) */
