/* Generated By:JJTree: Do not edit this line. NodeUnaryExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Node,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.schotanus.turtle.parser;

public
class NodeUnaryExpression extends SimpleNode {
  private double sign = 1.0;
  
  public NodeUnaryExpression(int id) {
    super(id);
  }

  public NodeUnaryExpression(TurtleParser p, int id) {
    super(p, id);
  }

  public void setSign(double sign) {
    this.sign = sign;
}

  public void interpret() throws InterpretationException {
    jjtGetChild(0).interpret();
    if (sign == -1.0) {
      double value = ((Double)expressionStack.pop()).doubleValue();
      expressionStack.push(Double.valueOf(sign * value));
    }
  }
}
/* JavaCC - OriginalChecksum=6b17b74b76d901f6c2fcdab037ba5442 (do not edit this line) */
