/* Generated By:JJTree: Do not edit this line. NodeStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Node,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.schotanus.turtle.parser;

public
class NodeStatement extends SimpleNode {
  public NodeStatement(int id) {
    super(id);
  }

  public NodeStatement(TurtleParser p, int id) {
    super(p, id);
  }
  
  public void interpret() throws InterpretationException {
    jjtGetChild(0).interpret();
  }
}
/* JavaCC - OriginalChecksum=d80bb7dc50b25c3351466abf81e8c5a7 (do not edit this line) */
