/* Generated By:JJTree: Do not edit this line. NodeGreaterThanOrEqualToExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Node,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.schotanus.turtle.parser;

public
class NodeGreaterThanOrEqualToExpression extends SimpleNode {
  public NodeGreaterThanOrEqualToExpression(int id) {
    super(id);
  }

  public NodeGreaterThanOrEqualToExpression(TurtleParser p, int id) {
    super(p, id);
  }

  /**
   * Interprets: expression1 >= expression2
   * <br>Both expressions are interpreted and popped from the stack. The
   * Boolean result is pushed on the stack.
   */
  public void interpret() throws InterpretationException {
    jjtGetChild(0).interpret();
    double leftOperand = ((Double)expressionStack.pop()).doubleValue();
    jjtGetChild(1).interpret();
    double rightOperand = ((Double)expressionStack.pop()).doubleValue();
    expressionStack.push(new Boolean(leftOperand >= rightOperand));
  }
}
/* JavaCC - OriginalChecksum=b527a3e762ca2e7f505fe1968ea16ea5 (do not edit this line) */
