/* Generated By:JJTree: Do not edit this line. NodeUseTurtleStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Node,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.schotanus.turtle.parser;

public
class NodeUseTurtleStatement extends SimpleNode {
  public NodeUseTurtleStatement(int id) {
    super(id);
  }

  public NodeUseTurtleStatement(TurtleParser p, int id) {
    super(p, id);
  }

  public void interpret() throws InterpretationException {
    jjtGetChild(0).interpret();
    int turtle = ((Double)expressionStack.pop()).intValue();
    turtleTerritoryModel.setActiveTurtle(turtle);
  }

}
/* JavaCC - OriginalChecksum=9b1ff6ec3f9700c3ef0bb4b3f735999a (do not edit this line) */
