/* Generated By:JJTree: Do not edit this line. SimpleNode.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Node,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.schotanus.turtle.parser;

import java.util.Hashtable;
import java.util.Stack;

import com.schotanus.turtle.TurtleApp;
import com.schotanus.turtle.model.TurtleModel;
import com.schotanus.turtle.model.TurtleTerritoryModel;

public abstract class SimpleNode implements Node {

  protected Node parent;
  protected Node[] children;
  protected int id;
  protected Object value;
  protected TurtleParser parser;

  public SimpleNode(int i) {
    id = i;
  }

  public SimpleNode(TurtleParser p, int i) {
    this(i);
    parser = p;
  }

  public void jjtOpen() {
  }

  public void jjtClose() {
  }

  public void jjtSetParent(Node n) { parent = n; }
  public Node jjtGetParent() { return parent; }

  public void jjtAddChild(Node n, int i) {
    if (children == null) {
      children = new Node[i + 1];
    } else if (i >= children.length) {
      Node c[] = new Node[i + 1];
      System.arraycopy(children, 0, c, 0, children.length);
      children = c;
    }
    children[i] = n;
  }

  public Node jjtGetChild(int i) {
    return children[i];
  }

  public int jjtGetNumChildren() {
    return (children == null) ? 0 : children.length;
  }

  public void jjtSetValue(Object value) { this.value = value; }
  public Object jjtGetValue() { return value; }

  /* You can override these two methods in subclasses of SimpleNode to
     customize the way the node appears when the tree is dumped.  If
     your output uses more than one line you should override
     toString(String), otherwise overriding toString() is probably all
     you need to do. */

  public String toString() {
    return TurtleParserTreeConstants.jjtNodeName[id];
  }
  public String toString(String prefix) { return prefix + toString(); }

  /* Override this method if you want to customize how the node dumps
     out its children. */

  public void dump(String prefix) {
    System.out.println(toString(prefix));
    if (children != null) {
      for (int i = 0; i < children.length; ++i) {
        SimpleNode n = (SimpleNode)children[i];
        if (n != null) {
          n.dump(prefix + " ");
        }
      }
    }
  }

  public int getId() {
    return id;
  }

  protected static Stack expressionStack = new Stack();
  protected static Stack functionCallStack = new Stack();
  protected static Stack repCountStack = new Stack();
  protected static Hashtable functions = new Hashtable();

  protected TurtleTerritoryModel turtleTerritoryModel =
      TurtleApp.getTurtleTerritoryModel();
  protected TurtleModel [] turtleModels =
      turtleTerritoryModel.getTurtleModels();

  protected TurtleModel getActiveTurtleModel() {
    return turtleModels[turtleTerritoryModel.getActiveTurtle()];
  }
}

/* JavaCC - OriginalChecksum=fa44ec8af7336c05688737191c127eff (do not edit this line) */
