/* Generated By:JavaCC: Do not edit this line. TurtleParserTreeConstants.java Version 7.0.10 */
package com.schotanus.turtle.parser;

public interface TurtleParserTreeConstants
{
  public int JJTPARSEUNIT = 0;
  public int JJTFUNCTIONDECLARATION = 1;
  public int JJTFORMALARGUMENTS = 2;
  public int JJTSTATEMENTBLOCK = 3;
  public int JJTSTATEMENT = 4;
  public int JJTBACKGROUNDCOLORSTATEMENT = 5;
  public int JJTBACKORFORWARDSTATEMENT = 6;
  public int JJTCLEARSTATEMENT = 7;
  public int JJTFUNCTIONCALL = 8;
  public int JJTACTUALARGUMENTS = 9;
  public int JJTHEADSTATEMENT = 10;
  public int JJTHOMESTATEMENT = 11;
  public int JJTIFSTATEMENT = 12;
  public int JJTLEFTORRIGHTSTATEMENT = 13;
  public int JJTVOID = 14;
  public int JJTPENUPORDOWNSTATEMENT = 15;
  public int JJTPENCOLORSTATEMENT = 16;
  public int JJTPENPOSITIONSTATEMENT = 17;
  public int JJTPENXPOSITIONSTATEMENT = 18;
  public int JJTPENYPOSITIONSTATEMENT = 19;
  public int JJTPRINTSTATEMENT = 20;
  public int JJTSTRINGLITERAL = 21;
  public int JJTREPEATSTATEMENT = 22;
  public int JJTSHOWORHIDETURTLESTATEMENT = 23;
  public int JJTUSETURTLESTATEMENT = 24;
  public int JJTWHILESTATEMENT = 25;
  public int JJTEQUALTOEXPRESSION = 26;
  public int JJTLESSTHANEXPRESSION = 27;
  public int JJTLESSTHANOREQUALTOEXPRESSION = 28;
  public int JJTGREATERTHANEXPRESSION = 29;
  public int JJTGREATERTHANOREQUALTOEXPRESSION = 30;
  public int JJTUNEQUALTOEXPRESSION = 31;
  public int JJTADDEXPRESSION = 32;
  public int JJTSUBTRACTEXPRESSION = 33;
  public int JJTMULTIPLYEXPRESSION = 34;
  public int JJTDIVIDEEXPRESSION = 35;
  public int JJTPOWEREXPRESSION = 36;
  public int JJTUNARYEXPRESSION = 37;
  public int JJTSINEFUNCTION = 38;
  public int JJTCOSINEFUNCTION = 39;
  public int JJTCONSTANT = 40;
  public int JJTREPCOUNT = 41;
  public int JJTVARIABLE = 42;


  public String[] jjtNodeName = {
    "ParseUnit",
    "FunctionDeclaration",
    "FormalArguments",
    "StatementBlock",
    "Statement",
    "BackgroundColorStatement",
    "BackOrForwardStatement",
    "ClearStatement",
    "FunctionCall",
    "ActualArguments",
    "HeadStatement",
    "HomeStatement",
    "IfStatement",
    "LeftOrRightStatement",
    "void",
    "PenUpOrDownStatement",
    "PenColorStatement",
    "PenPositionStatement",
    "PenXPositionStatement",
    "PenYPositionStatement",
    "PrintStatement",
    "StringLiteral",
    "RepeatStatement",
    "ShowOrHideTurtleStatement",
    "UseTurtleStatement",
    "WhileStatement",
    "EqualToExpression",
    "LessThanExpression",
    "LessThanOrEqualToExpression",
    "GreaterThanExpression",
    "GreaterThanOrEqualToExpression",
    "UnequalToExpression",
    "AddExpression",
    "SubtractExpression",
    "MultiplyExpression",
    "DivideExpression",
    "PowerExpression",
    "UnaryExpression",
    "SineFunction",
    "CosineFunction",
    "Constant",
    "RepCount",
    "Variable",
  };
}
/* JavaCC - OriginalChecksum=dd7adb85c80b6cdcefbcd07a1ddb40c6 (do not edit this line) */
